# mkdocs.yml
site_name: "A h'y Hikari guide"
repo_url: https://github.com/FasterSpeeding/HG
theme:
  name: material
  features:
    - navigation.prune
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.snippets:
      dedent_subsections: true
  - pymdownx.superfences
  # - markdown_include.include
  - toc:
      permalink: "#"

plugins:
  - autorefs
  - search
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3.13/objects.inv
            - https://docs.hikari-py.dev/en/latest/objects.inv
            - https://tanjun.cursed.solutions/objects.inv
            - https://tanchan.cursed.solutions/objects.inv
            - https://yuyo.cursed.solutions/objects.inv

watch:
  - docs_src
