bot_actions = ["Resync piped", "Reformat PR code"]
default_sessions = ["reformat", "verify-markup", "spell-check"]
hide = [
    "verify-deps",
    "flake8",
    "flake8",
    "slot-check",
    "build",
    "update-licence",
    "publish",
    "test-publish",
    "test",
    "test-coverage",
    "type-check",
    "verify-types",
]
top_level_targets = []

[github_actions.lint]
[github_actions.pr_docs]
[github_actions.reformat]
[github_actions.release_docs]
BRANCH_PUSHES = ["master"]

[github_actions.resync_piped]
