name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    uses: FasterSpeeding/Piped/.github/workflows/lint.yml@9c2b284f6fb48a4b294728b63fa4032b15104e00
    with:
      sessions: "verify-markup spell-check lint"
