name: Publish documentation

on:
  workflow_dispatch:
  push:
    branches: [master]
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types:
      - published

jobs:
  publish-docs:
    uses: FasterSpeeding/Piped/.github/workflows/release-docs.yml@7f5789a5b500b5ea084370b88f9ff7716de03d65
    secrets: inherit
